import { DEFAULT_API_URL, DEFAULT_MCP_SERVERS, DEFAULT_RITA_URL } from "./config";

/**
 * The Tauri HTTP allowlist, as the frontend can see it.
 *
 * `plugin-http` refuses any URL outside the capability scope compiled into the
 * binary. That scope is generated by scripts/generate-capabilities.mjs from the
 * same three environment variables read here, so the frontend can predict a
 * refusal instead of only reporting one after the fact.
 *
 * This mirrors the generator rather than reading the capability file, which is
 * compiled in and not available at runtime. If the generator's host derivation
 * changes, this has to change with it — the shared input is .env.local.
 */

interface ConfiguredOrigin {
  protocol: string;
  hostname: string;
}

/**
 * Scheme + hostname pairs this build can reach, derived exactly as the
 * generator derives them (same three env vars, same skip-on-malformed
 * behaviour). Kept separate from {@link configuredHosts} because the
 * allowlist itself is scheme-specific -- a host configured over https does
 * not admit http, matching how the generator writes the capability file
 * (Task 8 merge: ported from desk's `capabilityScope.ts`, which read the
 * compiled capabilities file's `http:default` globs -- those globs carry the
 * scheme too, e.g. `https://host/*`, not just the host).
 */
function configuredOrigins(): ConfiguredOrigin[] {
  const urls = [DEFAULT_API_URL, DEFAULT_RITA_URL, ...DEFAULT_MCP_SERVERS.map((s) => s.url)];
  const origins: ConfiguredOrigin[] = [];
  const seen = new Set<string>();
  for (const raw of urls) {
    if (!raw) continue;
    let protocol: string, hostname: string;
    try {
      ({ protocol, hostname } = new URL(raw));
    } catch {
      // A malformed value is skipped by the generator too, so it contributes
      // nothing to the scope either.
      continue;
    }
    const key = `${protocol}//${hostname}`;
    if (!seen.has(key)) {
      seen.add(key);
      origins.push({ protocol, hostname });
    }
  }
  return origins;
}

/** Hostnames this build can reach, derived exactly as the generator derives them. */
export function configuredHosts(): string[] {
  return [...new Set(configuredOrigins().map((o) => o.hostname))].sort();
}

/**
 * Whether a URL is inside this build's allowlist.
 *
 * Checks scheme as well as hostname: the compiled capability grants
 * `https://host/*`, not `*://host/*`, so a host configured over https that
 * is requested over http is genuinely out of scope and would be refused at
 * the Tauri IPC layer despite the hostname matching (desk-only check, Task 8
 * merge -- qwen's original version matched on hostname alone).
 *
 * With nothing configured the generator falls back to `https://*.ts.net/*`
 * (https only), so that case is matched here too -- otherwise a fresh clone
 * would warn about every tailnet host it can in fact reach.
 */
export function isHostAllowed(url: string): boolean {
  let protocol: string, hostname: string;
  try {
    ({ protocol, hostname } = new URL(url));
  } catch {
    return false;
  }

  const origins = configuredOrigins();
  if (origins.length === 0) return protocol === "https:" && hostname.endsWith(".ts.net");
  return origins.some((o) => o.protocol === protocol && o.hostname === hostname);
}

/** plugin-http's wording when a request falls outside the capability scope. */
export function isScopeError(e: unknown): boolean {
  return /not allowed on the configured scope/i.test(
    e instanceof Error ? e.message : String(e)
  );
}

/**
 * Replaces plugin-http's accurate but unactionable refusal.
 *
 * The original names the URL and stops there, which leaves the reader to
 * discover that the allowlist is compiled in, that it comes from .env.local,
 * and that changing it needs a rebuild — none of which is guessable from
 * "url not allowed on the configured scope".
 */
export function scopeErrorMessage(url: string): string {
  let host = url;
  try {
    host = new URL(url).hostname;
  } catch {
    /* keep the raw string */
  }

  const configured = configuredHosts();
  const allowed = configured.length
    ? `This build allows: ${configured.join(", ")}.`
    : "This build has no endpoints configured, so it allows only *.ts.net.";

  return (
    `Cannot reach ${host} — it is not in this build's HTTP allowlist. ${allowed} ` +
    `The allowlist is compiled into the app from .env.local, so add the host there ` +
    `(VITE_OPENBB_API_URL, VITE_RITA_URL or VITE_MCP_SERVERS) and rebuild. ` +
    `In dev, restart the app afterwards — regenerating capabilities is not hot-reloaded.`
  );
}

/** Rethrows a scope refusal with an actionable message; passes anything else through. */
export function rethrowWithScopeHelp(e: unknown, url: string): never {
  if (isScopeError(e)) throw new Error(scopeErrorMessage(url));
  throw e;
}
