"""Every payload BDOBB can produce must be one the bridge accepts.

The fixture (tests/fixtures/bdobb_payloads.json) is generated by
src/lib/chatShare.test.ts from a real call into shareWidgetToSymphony -- it is
not hand-written here. If this test fails, the client and the service have
drifted, which is exactly what this file exists to catch: putting the bridge
in the same repo as BDOBB was justified almost entirely by making that drift
impossible instead of merely unlikely.

Regenerate the fixture after any change to chatShare.ts:

    npx vitest run src/lib/chatShare.test.ts   # from the repo root

...and commit the result alongside this file.
"""

import json
import os
import pathlib

import pytest
from fastapi.testclient import TestClient

from app.fake_client import FakeClient
from app.main import create_app

FIXTURE = pathlib.Path(__file__).parent / "fixtures" / "bdobb_payloads.json"

# TestClient's default base_url ("http://testserver") carries a Host header
# that the app-wide DNS-rebinding allowlist (app/main.py's _HostOriginGate)
# rejects -- every request would 421 before ever reaching the handler under
# test. Match tests/test_messages.py's own workaround.
_BASE_URL = "http://127.0.0.1:8099"

# Every CI system worth worrying about (GitHub Actions included) sets this
# unconditionally. Used only to turn a missing fixture from a quiet skip into
# a hard failure in CI -- see test_fixture_is_committed below.
_IN_CI = bool(os.environ.get("CI"))


def load_payloads() -> dict[str, dict]:
    if not FIXTURE.exists():
        pytest.skip(
            f"{FIXTURE} not found; run `npx vitest run src/lib/chatShare.test.ts` "
            "from the repo root to regenerate it, then rerun this suite."
        )
    return json.loads(FIXTURE.read_text())


def test_fixture_is_committed():
    """A skipped contract test is invisible in an otherwise-green CI run --
    worse than no test at all, since it *looks* like coverage that isn't
    there. This test is never itself skipped: in CI it fails loudly if the
    fixture is missing, rather than letting the parametrized tests below
    quietly no-op via load_payloads()'s skip."""
    if not FIXTURE.exists() and _IN_CI:
        pytest.fail(
            f"{FIXTURE} is missing in CI. It must be generated by "
            "`npx vitest run src/lib/chatShare.test.ts` and committed to the repo -- "
            "the contract test proves nothing without it."
        )


@pytest.mark.parametrize("name", ["note", "table", "chart"])
def test_bridge_accepts_every_bdobb_payload(name: str):
    payloads = load_payloads()
    assert name in payloads, (
        f"fixture has no {name!r} payload; chatShare.test.ts must cover every "
        "SymphonyShareKind the client supports"
    )
    fake = FakeClient()
    api = TestClient(create_app({"BRIDGE_FAKE": "1"}, client=fake), base_url=_BASE_URL)

    res = api.post("/messages", json=payloads[name])

    assert res.status_code == 200, res.text
    assert len(fake.sent) == 1


def test_every_payload_carries_a_stream_id():
    for payload in load_payloads().values():
        assert payload["streamId"]
